cta:
  version: null
  bucket: null
  domain: null
layout_spectrum: 0.9649123
favicon: null
name: dhtest
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.5165078635327518
  lightness: 0.7681704
  saturation: 0.8778195
  rhythmicContrast: 0.08897243
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
typography_spectrum: 0.987328978953883
